version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-api
    ports:
      - "9800:9800"
    environment:
      - APP_NAME=GolangAppApi
      - APP_ENV=production
      - APP_PORT=9800
      - DB_HOST=db
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=db_golang
      - DB_PORT=3307
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - golang-network

  db:
    image: mysql:8.0
    container_name: golang-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=db_golang
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - golang-network

networks:
  golang-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local